{
  description = "Template based nixconfig from nix-starter-config";
  # test build with > nixos-rebuild dry-build --flake .#minifridge
  # home-manager switch --flake .#username@hostname
  # when console yells that hm config is different version, try using
  # nix build .#homeConfigurations.me.activationPackage && result/activate
  # running > ./result/bin/home-manager-generation
  # which is a link to the activation package in the current nixos system
  # also worked when followed by home-manager switch as normal
  # !! The actual solution was specifying the release version 24.11 in the url below...

  inputs = {
    # Nixpkgs
    nixpkgs.url = "github:nixos/nixpkgs/nixos-26.05";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    nix-flatpak.url = "github:gmodena/nix-flatpak/?ref=v0.4.1";

    # Home manager
    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    hardware.url = "github:nixos/nixos-hardware";

    firefox-addons = {
      url = "gitlab:rycee/nur-expressions?dir=pkgs/firefox-addons";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    firefox-gnome-theme = {
      url = "github:rafaelmardojai/firefox-gnome-theme";
      flake = false;
    };

    flake-utils.url = "github:numtide/flake-utils";

    # Another repository to hold development flakes, could be integrated into this one
    rust-devShells = {
      url = "github:AbrasiveAlmond/rust-dev-flake";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };

    python-devShells = {
      url = "github:AbrasiveAlmond/python-flake";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.flake-utils.follows = "flake-utils";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      nixpkgs-unstable,
      home-manager,
      nix-flatpak,
      ...
    }@inputs:
    let
      inherit (self) outputs;
      system = "x86_64-linux";
      # This is a function that generates an attribute by calling a function you
      # pass to it, with each system as an argument
      # forAllSystems = nixpkgs.lib.genAttrs systems;

      # The nixpkgs.config.* options in your NixOS configuration will set up the
      #  Nixpkgs instance that gets generated by lib.nixosSystem (aka pkgs),
      #  any external instance of Nixpkgs must be configured separately.
      pkgs-unstable = import nixpkgs-unstable {
        inherit system;
        config.allowUnfree = true;
      };

      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };

      devShells = import ./devshells {
        inherit pkgs;
      };
    in
    {
      devShells.${system} = devShells;
      # NixOS configuration entrypoint
      # Available through 'nixos-rebuild --flake .#your-hostname'
      nixosConfigurations = {
        # Main desktop
        minifridge = nixpkgs.lib.nixosSystem {
          specialArgs = {
            inherit inputs outputs self;
            inherit pkgs-unstable;
          };

          modules = [
            ./hosts/minifridge/configuration.nix
          ];
        };

        # Dell Inspiron 5502
        mainframe = nixpkgs.lib.nixosSystem {
          specialArgs = {
            inherit inputs outputs self;
            inherit pkgs-unstable;
          };

          modules = [
            ./hosts/mainframe/configuration.nix
          ];
        };
      };

      # Standalone home-manager configuration entrypoint
      # Available through 'home-manager --flake .#your-username@your-hostname'
      homeConfigurations = {
        # Personal Desktop
        "quinnieboi@minifridge" = home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
          extraSpecialArgs = {
            inherit inputs outputs nix-flatpak;
            inherit pkgs-unstable;
          };

          modules = [
            ./hosts/minifridge/home.nix
            nix-flatpak.homeManagerModules.nix-flatpak
          ];
        };
      };
    };
}
